"""add last_message_at to chat

Revision ID: 841b59d8f40d
Revises: 086190fc361a
Create Date: 2025-02-16 14:04:00.519442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '841b59d8f40d'
down_revision = '086190fc361a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_message_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_column('last_message_at')

    # ### end Alembic commands ###
