"""Add OAuth model

Revision ID: 92717ebf7d07
Revises: 1782cc506e85
Create Date: 2025-03-10 21:02:04.904666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92717ebf7d07'
down_revision = '1782cc506e85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.alter_column('full_payment_made',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.alter_column('full_payment_made',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###
